### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by JesusMayuri7** [flexmonster/pivot-flutter#1]
please add support for desktop windows.

thank you

**Comment by solja484** [comment]
Hello, JesusMayuri7!


Kindly note that currently, we are not planning to add support for Flutter Desktop.
However, if you need a desktop application solution, we recommend checking out our integration with Electron.js: https://www.flexmonster.com/doc/integration-with-electron-js/.


Kind regards,
Solomiia
